# Generated by Django 6.1.1 on 2026-09-29 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(max_length=50, unique=True)),
                ('blood_group', models.CharField(blank=True, default='O+', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academics.batch')),
                ('current_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_students', to='academics.semester')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academics.department')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academics.programme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['register_number'],
                'indexes': [models.Index(fields=['register_number'], name='students_st_registe_37f138_idx'), models.Index(fields=['department'], name='students_st_departm_123078_idx'), models.Index(fields=['batch'], name='students_st_batch_i_8467b1_idx'), models.Index(fields=['current_semester'], name='students_st_current_778a74_idx')],
            },
        ),
    ]
