# Generated by Django 6.1.1 on 2026-09-29 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facultysubjectassignment',
            name='staff_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programme',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='academics.department'),
        ),
        migrations.AddField(
            model_name='batch',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='academics.programme'),
        ),
        migrations.AddField(
            model_name='batch',
            name='regulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='academics.regulation'),
        ),
        migrations.AddField(
            model_name='semester',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.batch'),
        ),
        migrations.AddField(
            model_name='semestersubject',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_subjects', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='facultysubjectassignment',
            name='semester_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_assignments', to='academics.semestersubject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.department'),
        ),
        migrations.AddField(
            model_name='semestersubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_usages', to='academics.subject'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['regulation', 'programme'], name='academics_b_regulat_0a27aa_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['start_year', 'end_year'], name='academics_b_start_y_dd78b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('regulation', 'programme', 'start_year')},
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['batch', 'semester_number'], name='academics_s_batch_i_eb7cd1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('batch', 'semester_number')},
        ),
        migrations.AlterUniqueTogether(
            name='facultysubjectassignment',
            unique_together={('semester_subject', 'staff_user')},
        ),
        migrations.AddIndex(
            model_name='semestersubject',
            index=models.Index(fields=['semester', 'subject'], name='academics_s_semeste_5a6c50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='semestersubject',
            unique_together={('semester', 'subject')},
        ),
    ]
