# Generated by Django 6.1.1 on 2026-09-29 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('marks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mark',
            name='grade',
            field=models.CharField(blank=True, choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C', 'C'), ('AR', 'AR')], max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('semester_subject', 'name')},
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['semester_subject', 'name'], name='marks_asses_semeste_b59172_idx'),
        ),
    ]
