# Generated by Django 6.1.1 on 2026-09-29 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(default='Krishnasamy College of Engineering & Technology', max_length=200)),
                ('short_name', models.CharField(default='KCET', max_length=50)),
                ('tagline', models.CharField(default='Excellence in Engineering Education', max_length=300)),
                ('affiliation_text', models.CharField(default='Affiliated to Anna University', max_length=300)),
                ('accreditation_text', models.CharField(default='Accredited by NAAC • Approved by AICTE', max_length=300)),
                ('website_url', models.URLField(blank=True, default='https://www.kcet.in')),
                ('address_line_1', models.CharField(default='Anand Nagar, Nellikuppam Main Road', max_length=200)),
                ('address_line_2', models.CharField(blank=True, default='S. Kumarapuram', max_length=200)),
                ('city', models.CharField(default='Cuddalore', max_length=100)),
                ('district', models.CharField(blank=True, default='Cuddalore', max_length=100)),
                ('postal_code', models.CharField(default='607 109', max_length=20)),
                ('phone', models.CharField(default='04142-285601 to 285604', max_length=100)),
                ('email', models.EmailField(blank=True, default='info@kcet.in', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/logos/')),
                ('login_background', models.ImageField(blank=True, null=True, upload_to='branding/backgrounds/')),
                ('background_position', models.CharField(blank=True, default='center center', max_length=50)),
                ('background_overlay_opacity', models.FloatField(default=0.55)),
                ('login_title', models.CharField(default='KCET ERP', max_length=200)),
                ('login_subtitle', models.CharField(default='Academic Management System', max_length=300)),
                ('login_description', models.CharField(blank=True, default='Sign in to access the KCET Academic ERP Portal', max_length=500)),
                ('username_label', models.CharField(default='Email / Staff Code / Register Number', max_length=200)),
                ('username_placeholder', models.CharField(default='Enter your email or register number', max_length=200)),
                ('password_label', models.CharField(default='Password', max_length=100)),
                ('password_placeholder', models.CharField(default='Enter your password', max_length=100)),
                ('login_button_text', models.CharField(default='Sign In to KCET ERP', max_length=100)),
                ('footer_text', models.CharField(blank=True, default='© 2026 Krishnasamy College of Engineering & Technology. All rights reserved.', max_length=500)),
                ('primary_color', models.CharField(default='hsl(215, 72%, 43%)', max_length=30)),
                ('secondary_color', models.CharField(default='hsl(222, 36%, 14%)', max_length=30)),
                ('accent_color', models.CharField(default='hsl(215, 75%, 60%)', max_length=30)),
                ('background_color', models.CharField(default='hsl(210, 24%, 97%)', max_length=30)),
                ('text_color', models.CharField(default='hsl(222, 30%, 14%)', max_length=30)),
                ('border_color', models.CharField(default='hsl(214, 18%, 84%)', max_length=30)),
                ('show_logo', models.BooleanField(default=True)),
                ('show_institutional_info', models.BooleanField(default=True)),
                ('show_password_toggle', models.BooleanField(default=True)),
                ('show_development_credentials', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Website Settings',
                'verbose_name_plural': 'Website Settings',
            },
        ),
    ]
